#coding=utf-8

import json
from xml.dom.minidom import getDOMImplementation

# 解析 iconfont.cn 下载下来的 json，写入为 android string resource

input = "iconfont.json"
output = "src/main/res/values/icons.xml"

dom = getDOMImplementation()
doc = dom.createDocument(None, "resources", None)
resources = doc.documentElement
ttf_info = json.load(open(input, "r"))

resources.appendChild(doc.createComment("generated by generate_icons.py"))
for item in ttf_info["glyphs"]:
    string_elem = doc.createElement("string")
    string_elem.setAttribute("name", "ic_"+ item["name"].replace("-","_"))
    string_elem.appendChild(doc.createTextNode("\\u" + item["unicode"]))
    resources.appendChild(string_elem)

doc.writexml(open(output, "w"), indent="\n", addindent="\t", encoding="utf-8")


